service:
  name: hello

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2
  stage: dev
  environment:
    PG_HOST: 18.218.49.94
    PG_USERNAME: postgres
    PG_PASSWORD: PS_DB071238
    PG_DATABASE: pw_prod
    PG_PORT: 5432
    PG_MAXPOOLS: 10

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
